#!/bin/bash 

# Installation script for sqlSec
# Jason Gerfen <jason.gerfen@gmail.com>

e="echo -en"
ver="v0.2.0"
txt_green='\e[1;32m'
txt_reset='\e[0m'

# Show usage menu
usage()
{
  cat << EOF

Usage: $0 [options]

OPTIONS:
   -h      Show this message
   -t      Install test database & perform automated test suite

EOF
}

${e} "${txt_green}sqlSec - A symmetric encryption / data rotation tool for MySQL${txt_reset}\n"
echo ""

# Tests disabled by default
test=0

# Parse and apply specified arugments
while getopts “ht” OPTION ; do
  case $OPTION in
    h)
      usage && exit 1 ;;
    t)
      test=1 ;;
    ?)
      usage && exit 1 ;;
  esac
done

# Y/N prompt function
function ask {
 while true; do
  if [ "${2:-}" = "Y" ]; then
   prompt="Y/n"
   default=Y
  elif [ "${2:-}" = "N" ]; then
   prompt="y/N"
   default=N
  else
   prompt="y/n"
   default=
  fi

  read -p "$1 [$prompt] " REPLY

  if [ -z "$REPLY" ]; then
   REPLY=$default
  fi
  case "$REPLY" in
   Y*|y*) return 0 ;;
   N*|n*) return 1 ;;
  esac
 done
}

echo "Creating necessary database creation objects..."
if [ -d ".install" ] ;
then
  touch .install/database-schema.sql
else
  mkdir .install
fi
cp -fr templates/*.sql .install/
echo ""

${e} "${txt_green}Database installation credentials${txt_reset}\n"
echo ""

read -p "Enter MySQL username: " mu;
read -sp "Enter root MySQL password: " pass;
echo ""
echo ""

# Determine server version and provide error regarding cryptographic modes
# when less than 5.6

${e} "${txt_green}Database settings${txt_reset}\n"
echo ""

read -p "Database server name [localhost]: " server
sed -i "s/{SERVER}/${server:=localhost}/g" .install/*.sql

# Setup test env if asked
if [ "${test}" == 1 ] ; then
  cp -fr tests/test-database.sql .install/

  # User defined database settings
  echo ""
  ${e} "${txt_green}Test environment settings${txt_reset}\n"
  echo ""

  read -p "Test server name [localhost]: " server
  sed -i "s/{SERVER}/${server:=localhost}/g" .install/*.sql

  read -p "Test database name [PKI]: " name
  sed -i "s/{NAME}/${name:=PKI}/g" .install/*.sql
  echo ""

  read -p "Test database read-write username [Administrator]: " admin
  sed -i "s/{ADMIN}/${admin:=Administrator}/g" .install/*.sql

  read -sp "Test database read-write password [Random]: " admin_pass
  tap="$(tr -cd '[:alnum:]' < /dev/urandom | fold -w25 | head -n1)";
  sed -i "s/{ADMIN_PW}/${admin_pass:=${tap}}/g" .install/*.sql

  echo ""
  read -p "Test database read-only username [Read_Only]: " ro
  sed -i "s/{RO}/${ro:=Read_Only}/g" .install/*.sql

  read -sp "Test database read-only password [Random]: " ro_pass
  tup="$(tr -cd '[:alnum:]' < /dev/urandom | fold -w25 | head -n1)";
  sed -i "s/{RO_PW}/${ro_pass:=${tup}}/g" .install/*.sql
  echo ""

  echo ""
  ${e} "${txt_green}Test database account info${txt_reset}\n"

  echo "  Test database server: ${server}"
  echo "  Test database name: ${name}"
  echo "  Test database read-write account: ${admin}"
  echo "  Test database read-write password: ${admin_pass}"
  echo "  Test database read-only account: ${ro}"
  echo "  Test database read-only password: ${ro_pass}"

  mysql -u ${mu} --password=${pass} < .install/test-database.sql
  mysql -u ${mu} --password=${pass} < .install/test-procs.sql
  echo ""
fi

PS3="Select database to use: "
db=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "show databases"|grep -v "information"|grep -v "performance"|grep -v "mysql"|grep -v "view"|grep -v "sqlSec*")

if [[ "${db}" =~ ERROR ]] ; then
  echo "Could not connect to database" && exit 1
fi

select name in ${db}; do
 if [ -n "${name}" ]; then
  sed -i "s/{NAME}/${name}/g" .install/*.sql
  echo ""
  break
 fi
done

read -p "Backup directory [/tmp]: " buf
sed -i "s={BUF}=${buf:=/tmp}=   g" .install/*.sql
echo ""

sp_user="$(tr -cd '[:alnum:]' < /dev/urandom | fold -w15 | head -n1)";
sed -i "s/{SP}/${sp_user}/g" .install/*.sql
sp_pass="$(tr -cd '[:alnum:]' < /dev/urandom | fold -w25 | head -n1)";
sed -i "s/{SP_PW}/${sp_pass}/g" .install/*.sql
key="$(tr -cd '[:alnum:]' < /dev/urandom | fold -w68 | head -n1)";
sed -i "s/{KEY}/${key}/g" .install/*.sql
sed -i "s/{VER}/${ver}/g" .install/*.sql

if ask "Create a backup? " Y; then
 d=$(date +"%Y-%m-%d")
 mysqldump -u ${mu} --password=${pass} --routines ${name} > ${buf}/${d}-${name}.sql
 echo "Backup created... ${buf}/${d}-${name}.sql"
fi
echo ""

echo "Creating database, users & permissions"
mysql -u ${mu} --password=${pass} < .install/sqlSec-schema.sql

echo "Creating key rotaton procedures"
mysql -u ${mu} --password=${pass} ${name} < .install/sqlSec-procs.sql
echo ""

${e} "${txt_green}Specify encrypted fields for database: ${name}${txt_reset}\n"
echo ""

cleanup(){
 echo "Cleaning up..."
 rm -fr .install/
 exit
}

fields(){
 table="${1}"
 PS3="Select field to enable encryption: "
 tables=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "describe ${table}" | awk '{print $1}')
 tables+=" Main"
 tables+=" Quit"
 select field in ${tables}; do
  case ${field} in
   "Main")
    tables
    break
    ;;
   "Quit")
    break
    ;;
   *)
    if [ -n "${field}" ]; then
     # Make sure there aren't any foreign keys on the field selected or we won't be able to convert the field to a BLOB column type
     chk=$(mysql -u ${mu} --password=${pass} ${name} -sss -e 'select count(*) AS total from information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "'${name}'" AND TABLE_NAME = "'${table}'" AND COLUMN_NAME = "'${field}'";')
     if [ "${chk}" -gt 0 ] ; then
       echo "A foreign key constraint exists for this field. Cannot use '${table}.${field}'"
     else
       mysql -u ${mu} --password=${pass} ${name} -sss -e 'ALTER TABLE `'${table}'` MODIFY `'${field}'` BLOB'
       mysql -u ${mu} --password=${pass} ${name} -sss -e 'INSERT INTO `sqlSec_map` (`tbl`, `field`) VALUES ("'${table}'", "'${field}'")'
     fi
     fields ${table}
    else
     echo "Invalid choice"
     fields ${table}
    fi
    ;;
  esac
 done
}

tables(){
 PS3="Select table to view fields: "
 tables=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "show tables" | awk '{ print $1 }' | grep -v "sqlSec" | grep -v "view")
 tables+=" Quit"
 select table in ${tables}; do
  case ${table} in
   "Quit")
    cleanup
    ;;
   *)
    if [ -n "${table}" ]; then
     fields ${table}
    else
     echo "Invalid choice"
     fields ${table}
    fi
    ;;
  esac
 done
}

tables
